#!/usr/bin/env python3
"""Parity checks for the exported speaker encoder (assets/spk_encoder.onnx).

Two jobs:

1. `python verify_spk.py ref.wav` — embed the file two ways and print cosines:
     a. our frontend (numpy, mirroring the Rust implementation: resample to
        16 kHz, -30 dBFS increase-only normalization, power spectrogram,
        resemblyzer partial windowing, NO VAD trim) + spk_encoder.onnx;
     b. the real resemblyzer package (if installed), which additionally does
        webrtcvad silence trimming.
   (a) vs (b) is expected > 0.99 on clean speech; the deliberate VAD deviation
   accounts for the gap. The Rust CLI must match (a) to > 0.999.

2. `python verify_spk.py --dump-fixture` — print the Rust unit-test fixture:
   the power spectrogram of a deterministic synthetic signal, computed by
   librosa. Paste into cli/src/dsp.rs when the frontend changes.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

SR = 16_000
N_FFT = 400
HOP = 160
PARTIAL_FRAMES = 160
FRAME_STEP = 77  # round((16000 / 1.3) / 160), resemblyzer rate=1.3
MIN_COVERAGE = 0.75


def power_spectrogram(wav: np.ndarray) -> np.ndarray:
    """|STFT|^2 with librosa semantics: periodic hann, centered, zero padding.

    Returns [frames, 201]. This is exactly what the Rust frontend computes and
    what spk_encoder.onnx consumes (the mel filterbank lives in the graph).
    """
    import librosa

    s = librosa.stft(
        wav, n_fft=N_FFT, hop_length=HOP, window="hann", center=True, pad_mode="constant"
    )
    return (np.abs(s) ** 2).T.astype(np.float32)


def normalize_volume(wav: np.ndarray, target_dbfs: float = -30.0) -> np.ndarray:
    """Resemblyzer's normalize_volume with increase_only=True."""
    mean_sq = float(np.mean(wav**2))
    if mean_sq <= 0.0:
        return wav
    change = target_dbfs - 10.0 * np.log10(mean_sq)
    if change < 0.0:
        return wav
    return wav * (10.0 ** (change / 20.0))


def partial_slices(n_samples: int) -> tuple[list[slice], int]:
    """Resemblyzer's compute_partial_slices: 160-frame windows every 77 frames.

    Returns (mel frame slices, padded wav length).
    """
    n_frames = int(np.ceil((n_samples + 1) / HOP))
    steps = max(1, n_frames - PARTIAL_FRAMES + FRAME_STEP + 1)
    mel_slices, wav_slices = [], []
    for i in range(0, steps, FRAME_STEP):
        mel_slices.append(slice(i, i + PARTIAL_FRAMES))
        wav_slices.append(slice(i * HOP, (i + PARTIAL_FRAMES) * HOP))
    last = wav_slices[-1]
    coverage = (n_samples - last.start) / (last.stop - last.start)
    if coverage < MIN_COVERAGE and len(mel_slices) > 1:
        mel_slices, wav_slices = mel_slices[:-1], wav_slices[:-1]
    return mel_slices, wav_slices[-1].stop


def embed_with_onnx(wav16k: np.ndarray, onnx_path: Path) -> np.ndarray:
    import onnxruntime as ort

    wav = normalize_volume(wav16k)
    slices, padded_len = partial_slices(len(wav))
    if padded_len > len(wav):
        wav = np.concatenate([wav, np.zeros(padded_len - len(wav), dtype=wav.dtype)])
    spec = power_spectrogram(wav)
    batch = np.stack([spec[s] for s in slices]).astype(np.float32)

    sess = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])
    partials = sess.run(["embedding"], {"power_spec": batch})[0]
    mean = partials.mean(axis=0)
    return mean / np.linalg.norm(mean)


def dump_fixture() -> None:
    """Rust fixture: power spectrogram of a deterministic two-tone signal.

    The Rust test regenerates the same signal; keep the formula in sync with
    `fixture_signal()` in cli/src/dsp.rs.
    """
    n = np.arange(800, dtype=np.float64)
    wav = (0.5 * np.sin(2 * np.pi * 440.0 * n / SR)
           + 0.25 * np.sin(2 * np.pi * 1000.0 * n / SR + 0.5)).astype(np.float32)
    spec = power_spectrogram(wav)
    print(f"// Generated by export/verify_spk.py --dump-fixture ({spec.shape[0]} frames).")
    for frame in (0, 3):
        vals = ", ".join(f"{v:.6e}" for v in spec[frame])
        print(f"const FIXTURE_FRAME_{frame}: [f32; 201] = [{vals}];")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("wav", nargs="?", type=Path)
    ap.add_argument("--onnx", type=Path,
                    default=Path(__file__).resolve().parent.parent / "assets/spk_encoder.onnx")
    ap.add_argument("--dump-fixture", action="store_true")
    ap.add_argument("--dump-embedding", type=Path, metavar="OUT_JSON",
                    help="write the frontend-(a) embedding as JSON (for the Rust parity test)")
    args = ap.parse_args()

    if args.dump_fixture:
        dump_fixture()
        return
    if args.wav is None:
        ap.error("pass a wav file or --dump-fixture")

    import librosa

    wav, sr = librosa.load(args.wav, sr=None, mono=True)
    if sr != SR:
        wav = librosa.resample(wav, orig_sr=sr, target_sr=SR)

    ours = embed_with_onnx(wav, args.onnx)
    print(f"onnx embedding: dim={ours.shape[0]}, norm={np.linalg.norm(ours):.6f}")
    if args.dump_embedding:
        import json
        args.dump_embedding.write_text(json.dumps([float(v) for v in ours]))
        print(f"wrote {args.dump_embedding}")

    try:
        from resemblyzer import VoiceEncoder, preprocess_wav
    except ImportError:
        print("resemblyzer not installed; skipping reference comparison "
              "(pip install resemblyzer)", file=sys.stderr)
        return
    ref = VoiceEncoder("cpu").embed_utterance(preprocess_wav(args.wav))
    cos = float(np.inner(ours, ref))
    print(f"cosine(ours, resemblyzer) = {cos:.6f}  (expect > 0.99; gap is the VAD trim)")
    if cos <= 0.99:
        sys.exit("FAIL: embedding parity below 0.99")


if __name__ == "__main__":
    main()
